### ISSUE TITLE
Remove FPS field from the page

### ISSUE THREAD

**Issue by Ayyyn** [lukeboi/scroll-viewer#6]
Since, fps formula recursively results in infinity due to very low `renderTime`: 
<img src="https://user-images.githubusercontent.com/91630937/231531051-95f39097-b64f-492b-b00d-9c6d39c05702.png" width=30% height=30%>
https://github.com/lukeboi/scroll-viewer/blob/767f26fc9123a063c241dfc8e353c56ac02c553b/js/volume-raycaster.js#L174
and the measure doesn't seem to be significant to display, fps field can be considered to be excluded from the page

**Comment by lukeboi** [comment]
Howdy! Totally agree it's not super useful, but I'm not sure I want to remove it entirely because when we add more features it'll be useful to see the render times. I concur that it's not the most useful thing ever, and I think it'd make sense to put it somewhere else on the UI.

**Comment by Ayyyn** [comment]
Yes, that seems doable!
